baseURL = "https://v9rt3x.io/"
languageCode = "en"
title = "Stephan's Blog"
theme = "aether"
#disqusShortname = "Your shortname for Disqus - optional"

[params]
brand = "v9rt3x"
description = "Music, Programming, Philosophy, Handcrafting"
#homeimg = "URL to the image used for the home button at the bottom of each post - optional"
#bgimg = "URL to the image used for the page background - optional"
#rssinmenu = whether you would like a RSS feed link to appear in the navigation menu (true, false) - optional
